source 'https://github.com/CocoaPods/Specs.git'
platform :ios,'8.0'
use_frameworks!

def pods
    pod 'ReactiveCocoa', '~> 5.0.0'
    pod 'ReactiveObjC', '~> 2.1.0'
    pod 'FMDB', '~> 2.6.2'
    pod 'AFNetworking', '~> 3.0'
    pod 'Alamofire', '~> 4.4'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'MJRefresh', '~> 3.1.0'
end

target 'LLMarkerDemo' do
    pods
end



